trigger:
  batch: true
  branches:
    include:
      - master
      - feature*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: AkkaSensors
  - name: IVY_HOME
    value: $(Pipeline.Workspace)/.ivy2

steps:

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
      cleanDestinationDirectory: false

  - task: Bash@3
    displayName: 'Building and testing 2.12'
    inputs:
      targetType: 'inline'
      script: |
        sbt -Divy.home=${IVY_HOME} -Dsbt.ivy.home=${IVY_HOME} "++2.12.17; test; "
      failOnStderr: false
