addSbtPlugin("org.scalameta"  % "sbt-scalafmt"  % "2.4.6")
addSbtPlugin("com.github.sbt" % "sbt-release"   % "1.4.0")
addSbtPlugin("com.github.sbt" % "sbt-pgp"       % "2.3.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"  % "3.12.2")
addSbtPlugin("no.arktekk.sbt" % "aether-deploy" % "0.29.1")
